version: "3"
services:

  db:
    image: postgres:9.6
    container_name: receipt-tracker-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes: # change this to your local folder
      - ~/Projects/DockerCache/Receipt-Tracker/:/var/lib/postgresql/data